trigger:
- '*'

variables:
  AZP_CACHING_TAR: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-20.04'
    mac:
      imageName: 'macos-10.15'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.101'
- task: DotNetCoreCLI@2
  displayName: Run Test Projects
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj'
    arguments: '--configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage'
    publishTestResults: true
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'
